- lib/analysis_component.coffee
- lib/utils.coffee
- package.json
This deprecation was introduced in pathwatcher 3.3.0:
https://github.com/atom/node-pathwatcher/commit/6d6f2666dabe581111808a8cbe856d8429f0f21b
Atom started pulling in pathwatcher 3.3.1 in version 0.180.0:
https://github.com/atom/atom/commit/c260a29434547493d5f22508e2afd2da96f13f40
> Replace exists() with existsSync() because it is deprecated.

- grammars/dart.cson
- lib/analysis/analysis_toolbar.html
Address #30 - make the errors view slightly smaller (and add some missing keywords to the grammar).
> make the errors view slightly smaller

- lib/analysis/analysis_toolbar.html
- lib/pub/pub_component.coffee
- lib/sdk/sdk_info.coffee
- lib/sdk/sdk_info.html
- more size tweaks to the error panel
- correct some (reversed) labels in the sdk info dialog
- add a `pub upgrade` command
fix #31
> add pub upgrade; change sdk info labels; adjust error view size

- README.md
- coffeelint.json
- lib/analysis/analysis_toolbar.coffee
- lib/analysis_result.coffee
- lib/dart-tools.coffee
- lib/formatter.coffee
- lib/info/problem_view.coffee
- lib/utils.coffee
- lib/views/analysis_view.coffee
- add a coffeescript lint file. It has some coffeelint warnings about use of `->`, but I'm not sure if they're accurate or not -
- lint nits about semicolons, indent, and trailing whitespace
- commented out a block of code which was throwing an exception (`lib/analysis/analysis_toolbar.coffee`)
I'll file an issue about the exception for more context -
> workaround exception; lint coffeescript files

- lib/utils.coffee
Fix for an exception I saw - the pubspec watcher was being passed a non-dart project. My workspace has a coffeescript project first and a dart project 2nd. This re-written `getDartProjectPaths()` filters out non-dart projects; not sure why the previous one wasn't though.
> getDartProjectPaths()

- .travis.yml
- README.md
Some initial support for building on travis. You'd still need to configure the the github hook for travis. But this will get the code being linted, and any tests put into `spec/` _should_ run.
> initial support for building on travis

- .coffeelintignore
- coffeelint.json
- lib/autocomplete/provider.coffee
- lib/formatter.coffee
- lib/pub/pub_component.coffee
- use the coffeescript lints from the main atom project (https://github.com/atom/atom/blob/master/coffeelint.json)
- some edits based on lint findings
Most of the remaining lints are to do with using `or` instead of `||` - using the more english word style comparison operators.
> more lints

- .editorconfig
- coffeelint.json
- lib/analysis/analysis_decorator.coffee
- lib/analysis_component.coffee
- lib/analysis_server.coffee
- add an editorconfig file
- change the `prefer_english_operator` lint to a warn from an error
- address some misc lints
> change the prefer_english_operator lint to a warn from an error

- CHANGELOG.md
- README.md
- lib/analysis_component.coffee
- lib/analysis_server.coffee
- lib/dart-tools.coffee
- lib/pub/pub_component.coffee
- lib/utils.coffee
dart-tools will boot up analysis server and attached GUI components on demand if a Dart file is opened but there is no `.packages` or `pubspec.yaml` path present.
Work on #23.
> On demand activation

- CHANGELOG.md
- lib/analysis/analysis_decorator.coffee
- lib/analysis/analysis_toolbar.html
- lib/info/problem_view.html
- lib/info/quick_info_view.coffee
- lib/info/quick_info_view.html
- styles/dart-tools.less
- add a gutter bullet decoration for dart infos, warnings, and errors
- show the quick error view for any markers on the line (not just the selection)
- change the quick info view of a dart issue (image follows)
- change the highlight decorator to better call out errors (2px underline instead of 1px dotted)
> revise the errors display

- lib/analysis/analysis_decorator.coffee
- lib/analysis/analysis_toolbar.coffee
- lib/dart-tools.coffee
- lib/info/problem_view.coffee
- lib/info/quick_info_view.coffee
- menus/dart-tools.cson
- fix https://github.com/radicaled/dart-tools/issues/54
- add documentation to clarify what the different analysis views and classes are used for
- remove a menu item that no longer went anywhere; add in the `SDK Info` menu item
> remove a deprecated menu item; add documentation

- CHANGELOG.md
- lib/info/quick_info_view.coffee
- lib/info/quick_info_view.html
- lib/pub/pub_status_view.coffee
- lib/pub/pub_status_view.html
- lib/sdk/sdk_info.coffee
- lib/sdk/sdk_info.html
- change the sdk info and pub dialogs to modal dialogs
This address an issue where we had several panels docked on the bottom with hidden contents. When hidden, the panels were 1 pixel high. This led to a really thick separator between the panel area and the editors.
before:
after:
> change the sdk info and pub dialogs to modal dialogs

- CHANGELOG.md
- lib/analysis_server.coffee
- lib/dart-tools.coffee
- lib/platform/platform_service.coffee
- lib/project/project_picker.coffee
- lib/project/project_picker.html
- lib/sdk/sdk_service.coffee
- lib/utils.coffee
- package.json
SdkService.discoverSdkPath tries to find the user's SDK path by
examining their PATH. This only works on Windows (theoretically) and
Atom instances that are launched from the shell (and thus inherit the
shell's PATH).
Closes #60
> Try to locate the user's SDK path when none provided

- lib/analysis_api/edit_api.coffee
The parameter is "lineLength" according to the new API
Closes #44
> Send the preferred line length to the analysis_server during formatting

- lib/analysis_api.coffee
According to the documentation, AddContentOverlay blows away the analysis_servers knowledge of the file and replaces it with the provided contents. However, when we use this in practice the analysis_server seems to completely forget about non-essential (hints, infos, warnings) errors. So now we do the same thing, but by using the ChangeContentOverlay instead.
Closes #74 (and several strange, unreported anamolies I noticed locally)
> Replace AddContentOverlay with ChangeContentOverlay.

- grammars/dart.cson
Very basic change. Just adds `enum` to the `keyword.declaration.dart` match.
> Added `enum` keyword to grammar.

- settings/dart.cson
This commit modifies the string that is prepended when the command `editor:toggle-line-comments` in Atom is executed on Dart source code. The new string is `// `.
> Made "//" the default comment start string.

- grammars/dart.cson
* Fixed highlighting of function names
* Added `enum`
* Allow constants to be preceded with an underscore and be one word
* Remove triple equals
* Lowercase `dynamic`
* Removed `String` from primitive types
> Several small grammar edits

- lib/linter/linter_component.coffee
deleteProjectMessages / setProjectMessages interface now does this for us.
> No need to manually refresh linter view anymore.

- CHANGELOG.md
- lib/dart-tools.coffee
This issue is complicated by the fact that call order seems to be static (activate, then call consumeLinter) in dev mode but seemingly random in production mode.
> Fix call order of consumeLinter
